### PR TITLE
Added sequential scan performance tests

### PR DESCRIPTION
**Pull request by dutow**

### CODE REVIEW

**Comment by dutow** [comment]
```
Sequential scan read times
==========================
HEAP: 1172.451
TDE: 1320.662
TDE_BASIC: 1980.203
```

**Review by dAdAbird — COMMENTED** [review]
LGTM
But it'd be nice to have a % overhead next to tde and tde_basic. Something like:
```
Sequential scan read times
==========================
HEAP: 1172.451
TDE: 1320.662 (+11.22%)
TDE_BASIC: 1980.203 (+40.80%)
```

**Comment by dAdAbird** [comment]
And maybe a number of rows in test data - just to have a bulpark estimation in mind when reading results

**Comment by dutow** [comment]
```
CSV entries: 1010312 pp-2019.csv
Sequential scan read times
==========================
HEAP: 1082.343
TDE: 1303.636 (120%)
TDE_BASIC: 1303.636 (157%)
```

**Review by dAdAbird — APPROVED** [review]

**Pull request merged**
